name: Lint report

on:
  workflow_call:

jobs:
  lint-report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd render_bundle && tox -e lint
