name: publish-bundle

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true
    inputs:
      bundle_variant:
        required: true
        type: string
      channel:
        required: false
        type: string
        default: 1.3/edge

jobs:
  publish-bundle:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install requirements
        run: pip3 install -r render_bundle/requirements.txt
      - name: render bundle.yaml
        run: python3 render_bundle/render_bundle.py --output_file bundle/bundle.yaml --bundle_variant=${{ inputs.bundle_variant }} --channel=${{ inputs.channel }}
      - name: Upload bundle
        uses: canonical/charming-actions/upload-bundle@2.6.1
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          bundle-path: "bundle"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ inputs.channel }}"
