name: CI workflow

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint-report:
    uses: ./.github/workflows/lint-report.yaml

  static-analysis:
    uses: ./.github/workflows/static-analysis.yaml

  unit-tests-with-coverage:
    uses: ./.github/workflows/unit-test.yaml

  publish-sdcore-up-bundle:
    name: Publish SDCORE-UP charm bundle
    needs:
      [lint-report, static-analysis, unit-tests-with-coverage]
#    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/publish-bundles.yaml
    with:
      bundle_variant: SDCORE_UP
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
